# Generated by Django 6.1.1 on 2026-09-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=10, help_text='Discount percentage applied to opted-in products')),
                ('banner_message', models.CharField(blank=True, max_length=250)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='offers', to='catalog.product')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
    ]
